#!/bin/bash
ADDON=${2:-$1}
wmctrl -l -p | awk '{print "echo `ps -p "$3"` + \""$0"\""}'  | grep -v "ps -p 0" | sh| grep " $1 +" | grep $ADDON | sed -e "s/^.*`hostname` //" | awk '{print "wmctrl -F -a \""$0"\""}' | sh
